#!/usr/bin/env Rscript
#
# prep_graph_cs3_unif.R
#
# Created: 2018-12-31
#  Author: Charles Zhu
#
# this prep script needs the preprocessed scenario file:
#   scenarios/graph_cs3_full.RData
# this file is generated by the preprocessor:
#   scnearios/prep_graph_cs3_full.R

suppressPackageStartupMessages(require(optparse))

load("scenarios/graph_cs3_full.RData")

opt_list = list(
    make_option(
        c("-O", "--output_file"),
        action = "store", default = NA, type = "character",
        help = "Output filename"),
    make_option(
        c("-s", "--random_seed"),
        action = "store", default = NA, type = "integer",
        help = "Random seed, default = %default"),
    make_option(
        c("-L", "--num_spots"),
        action = "store", default = NUM_SPOTS_FULL, type = "integer",
        help = "Number of spots, default = %default"),
    make_option(
        c("--weight_multiplier"),
        action = "store", default = 1, type = "integer",
        help = "Edge weight (movement time) multiplier, default = %default")
)
opt_obj = OptionParser(option_list = opt_list)
opt = parse_args(opt_obj)

if(is.na(opt$output_file)) {
    print_help(object = opt_obj)
    stop("Must specify output filename.")
}
if(is.na(opt$num_spots)) {
    print_help(object = opt_obj)
    stop("Must specify number of spots.")
}

stopifnot(!file.exists(opt$output_file))
stopifnot(file.create(opt$output_file))
stopifnot(opt$num_spots > 1L)
stopifnot(opt$num_spots <= NUM_SPOTS_FULL)
stopifnot(opt$weight_multiplier >= 1L)

NUM_SPOTS <<- opt$num_spots
lockBinding("NUM_SPOTS", globalenv())

if(!is.na(opt$random_seed)) {
    set.seed(opt$random_seed)
}

random_spots <- c(1L, sort(sample(2L:NUM_SPOTS_FULL, size = NUM_SPOTS - 1L)))
map_graph_distances <-
    map_graph_distances[random_spots, random_spots] * opt$weight_multiplier
# storage.mode(map_graph_distances) <- "integer"
stopifnot(is.integer(map_graph_distances))

suppressPackageStartupMessages(source("lib/graph_generator.R"))

map_alternative_graph <- graph_from_adjacency_matrix(
    adjmatrix   = map_graph_distances,
    mode        = "directed",
    weighted    = TRUE,
    diag        = FALSE
)

save(
    NUM_SPOTS,
    # map_graph_adj_matrix, map_graph,
    map_graph_distances, map_alternative_graph,
    file = opt$output_file
)
